Require Import interfaces.set algebra_notation.
Require Import interfaces.sprop logic.aprop relations.
Require Import set_lambda.
Require Import interfaces.orders interfaces.subset.
Require Import interfaces.topology interfaces.uniform.
Require Import theory.set orders.orders orders.subset orders.closure orders.filters.
Require Import orders.subset_images.
Require Import uniform.base uniform.basis.
Require Import easy rewrite simplify.

Local Open Scope topology_scope.

Section induced.
  Universes u.
  Context (A:Type@{u}) {eq:Equiv A}.
  Context {Λ:Type@{u}} (basis : Λ → A ∗ A → Ω).
  
  Class InducedUniformBasis : SProp :=
  { induced_ufm_refl  : ∀ i x, basis i (x, x)
  ; induced_ufm_sym   : ∀ i, ∐ j, ∏ x y,   basis j (y, x) ⊸ basis i (x, y)
  ; induced_ufm_split : ∀ i, ∐ j, ∏ x y z, basis j (x, y) ⊠ basis j (y, z) ⊸ basis i (x, z)
  ; induced_ufm_down  : ∀ i₁ i₂, ∐ i₃, ∏ p, basis i₃ p ⊸ basis i₁ p ∧ basis i₂ p
  ; induced_ufm_sep   : ∀ x y : A, x = y ⧟ ∏ i, basis i (x, y)
  ; induced_ufm_compat: ∀ i x x' y y', x = x' ⊠ basis i (x', y') ⊠ y' = y ⊸ basis i (x, y)
  }.
  
  Context (inhab : Inhabited Λ) `{!InducedUniformBasis}.

  Local Abbreviation sep := induced_ufm_sep.

  Local Instance induced_uniform_is_set : IsSet A.
  Proof. split.
  + intros x. rew (sep _ _). intros i. apply induced_ufm_refl.
  + intros x y. rew (sep _ _).
    rew <-all_adj. intros i.
    pose proof induced_ufm_sym i as [j Pj]. rew (all_lb _ j). exact (Pj y x).
  + intros x y z. rew (sep _ _).
    rew <-all_adj. intros i.
    pose proof induced_ufm_split i as [j Pj].
    rew (all_lb _ j). exact (Pj x y z).
  Qed.

  Local Canonical Structure induced_uniform_set : set := set_make A.
  Local Abbreviation X := induced_uniform_set.

  Local Instance induced_basis_isfun {i} : @IsFun (X ⊗ X) Ω (basis i).
  Proof. enough (∀ x x' y y', x = x' ⊠ y = y' ⊸ basis i (x, y) ⊸ basis i (x', y')) as P.
  + intros [x y][x' y']. apply aand_intro; [ apply P |].
    rew <-(P _ _ _ _). unfold_pair_eq; apply aprod_proper_aimpl; now apply symmetry.
  + intros x x' y y'. rew (symmetry_iff (=) x x'). rew <-(aprod_adj _ _ _).
    rew (aprod_assoc _ _ _), (aprod_com (y = y') _).
    apply induced_ufm_compat.
  Qed.

  Local Canonical Structure induced_basis i : 𝒫 (X ⊗ X) := func_make (basis i).

  (** The induced uniformity on X, generated by the basis. *)

  Local Instance induced_uniformity : Uniformity X
    := presented_uniformity induced_basis.

  Local Instance induced_uniformity_presentation : UniformityPresentation X induced_basis
    := presented_uniformity_prop _.

  Local Instance induced_uniform_space : UniformSpace X.
  Proof. split.
  + apply (presented_filter_filter_alt (H:=induced_uniformity_presentation)).
    intros i j. pose proof induced_ufm_down i j as [k P]. exists k. split; intros p;
    change (p ∊ induced_basis ?j) with (basis j p); now rew (P p : _ ⊸ _).
  + apply presented_pre_uniform_space; intros i.
    * intros [x y]. change ((x, y) ∊ id_rel _) with (x = y).
      rew (induced_ufm_sep x y). exact (all_lb _ i).
    * pose proof induced_ufm_sym i as [j P]. exists j. intros [x y]. exact (P x y).
    * pose proof induced_ufm_split i as [j P]. exists j. intros [x z].
      change ((∐ y, basis j (x, y) ⊠ basis j (y, z)) ⊸ basis i (x, z)).
      rew <-aex_adj; intros y. exact (P _ _ _).
  Qed.

  Lemma induced_separated_uniform_space : SeparatedUniformSpace X. 
  Proof. pose proof uniformity_presentation_basis_correct (X:=X).
    apply uniform_separated_by_basis. intros x y. now rew (sep _ _).
  Qed.
End induced.

